#
#    Copyright (c) 2025 Project CHIP Authors
#    Copyright 2025 NXP
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#

# This file is used to set configs or override default configurations for NXP platforms.
CONFIG_CHIP=y
CONFIG_BT_DEVICE_NAME="\"NXPAliroLock\""
CONFIG_CHIP_DEVICE_PRODUCT_NAME="Lock"
CONFIG_CHIP_DEVICE_TYPE=10
CONFIG_CHIP_CUSTOM_BLE_ADV_DATA=n
CONFIG_CHIP_APP_LED_WIDGET=n

CONFIG_NET_L2_OPENTHREAD=y
CONFIG_CHIP_IPV4=n
CONFIG_CHIP_OPENTHREAD_FTD=n
CONFIG_SLEEPY_END_DEVICE=y
CONFIG_CHIP_ENABLE_ICD_SUPPORT=y
CONFIG_CHIP_PERSISTENT_SUBSCRIPTIONS=y
CONFIG_NXP_ENABLE_ALIRO=y
CONFIG_CHIP_LIB_SHELL=n
CONFIG_ENABLE_FEEDBACK=n
CONFIG_CHIP_APP_UI_FEEDBACK=n
CONFIG_CHIP_APP_CUSTOMIZE_EXTRA_GATT_INFO=y
CONFIG_CHIP_APP_EXTRA_GATT_DB_HEADER="<aliro/ble/gatt_extra_db.h>"
CONFIG_CHIP_APP_EXTRA_GATT_UUID_HEADER="<aliro/ble/gatt_extra_uuid128.h>"

#SDK config
CONFIG_MCUX_PRJSEG_module.board.boardfile=n
CONFIG_MCUX_COMPONENT_utility.format=y
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.sensors=y
CONFIG_MCUX_COMPONENT_driver.lpspi_edma=y
CONFIG_MCUX_COMPONENT_driver.dma3=y
CONFIG_MCUX_COMPONENT_driver.lpi2c=y
CONFIG_CHIP_MBEDTLS_3X=y